cart/urls.py
from django.urls import path

from cart.views import CartDetailView, AddToCartView, RemoveFromCartView, clear_cart


app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', AddToCartView.as_view(), name='add'),
    path('remove/<slug:slug>/', RemoveFromCartView.as_view(), name='remove'),
    path('clear/', clear_cart, name='clear'),
]

coupons/urls.py
from django.urls import path
from coupons.views import CouponApplyView


app_name = 'coupons'

urlpatterns = [
    path('apply/', CouponApplyView.as_view(), name='apply'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderDetailsView, OrderCreateView, OrdersListView, admin_order_details, OrderDeleteView, \
    SuccessView, CancelView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('list/', OrdersListView.as_view(), name='order_list'),
    path('details/<int:order_id>/', OrderDetailsView.as_view(), name='order_details'),
    path('admin/order/<int:order_id>/', admin_order_details, name='admin_order_details'),
    path('<pk>/delete/', OrderDeleteView.as_view(), name='delete'),
    path('success/', SuccessView.as_view(), name='success'),
    path('cancel/', CancelView.as_view(), name='cancel')
]

shop/urls.py
from django.urls import path

from shop.views import (
    IndexTemplateView,
    CategoryProductsListView,
    DeliveryView,
    AboutView,
    ContactsView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('category/<slug:slug>/', CategoryProductsListView.as_view(), name='category_products'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

tyres_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from orders.views import StripeWebhookView
from shop.views import get_specifications


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('webhooks/stripe/', StripeWebhookView.as_view(), name='stripe_webhook'),
    path('get_specifications/<int:product_type_id>/', get_specifications, name='get_specifications'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include("django.conf.urls.i18n")),
    path('customers/', include('customers.urls', namespace='customers')),
    path('accounts/', include('allauth.urls')),  # Allauth
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class AddToCartForm(forms.Form):

    CHOICE_PRODUCT_QUANTITY = [(i, str(i)) for i in range(1, 11)]

    quantity = forms.TypedChoiceField(
        label=_('Quantity'),
        choices=CHOICE_PRODUCT_QUANTITY,
        coerce=int,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm'})
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.views import View
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _

from cart.cart import Cart
from cart.forms import AddToCartForm
from coupons.forms import CouponApplyForm
from shop.models import Product

CART_REDIRECT_URL = 'cart:detail'


class AddToCartView(View):
    product = None
    cart = None

    def dispatch(self, request, *args, **kwargs):
        self.cart = Cart(self.request)
        self.product = Product.objects.get(slug=self.kwargs['slug'])
        return super().dispatch(request, *args, **kwargs)

    def post(self, *args, **kwargs):
        form = AddToCartForm(self.request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            self.cart.add(product=self.product, quantity=cd['quantity'], update_quantity=cd['update'])
        return redirect(CART_REDIRECT_URL)

    def get(self, *args, **kwargs):
        self.cart.add(self.product)
        return redirect(self.request.META.get('HTTP_REFERER'))


class CartDetailView(TemplateView):
    template_name = 'cart/cart_detail.html'
    extra_context = {'title': _('Shop | Cart')}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['coupon_form'] = CouponApplyForm()
        return context


class RemoveFromCartView(View):
    def get(self, request, *args, **kwargs):
        cart = Cart(self.request)
        product = Product.objects.get(slug=kwargs.get('slug'))
        cart.remove(product)
        return redirect(CART_REDIRECT_URL)


def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect(CART_REDIRECT_URL)

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static shop_tags i18n %}
{% block content %}
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">
            <!--start breadcrumb-->
            <section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
                <div class="container">
                    <div class="page-breadcrumb d-flex align-items-center">
                        <h3 class="breadcrumb-title pe-3">{% trans 'Shop Cart' %}</h3>
                        <div class="ms-auto">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb mb-0 p-0">
                                    <li class="breadcrumb-item"><a href="{% url 'shop:index' %}"><i class="bx bx-home-alt"></i>
                                        {% trans 'Home' %}</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">{% trans 'Shop Cart' %}</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </section>
            <!--end breadcrumb-->
            <!--start shop cart-->
            <section class="py-4">
                <div class="container">
                    <div class="shop-cart">
                        <div class="row">
                            <div class="col-12 col-xl-8">
                                <div class="shop-cart-list mb-3 p-3">
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                            <div class="row align-items-center g-3">
                                                <div class="col-12 col-lg-6">
                                                    <div class="d-lg-flex align-items-center gap-2">
                                                        <div class="cart-img text-center text-lg-start">
                                                            {% get_main_image product as image %}
                                                        <a href="{{ product.get_absolute_url }}">
                                                            <img src="{{ image.url }}" width="130" alt="">
                                                        </a>
                                                        </div>
                                                        <div class="cart-detail text-center text-lg-start">
                                                            <a href="{{ product.get_absolute_url }}"><h6 class="mb-2">{{ product.name }}</h6></a>
                                                            <p class="mb-0">{% trans 'Diameter:' %} <span>{{ product.diameter }}</span>
                                                            </p>
                                                            <p class="mb-2">{% trans 'Price:' %} <span>${{ item.price }} x {{ item.quantity }}{% trans 'pcs.' %}</span>
                                                            </p>
                                                            <h5 class="mb-0">${{ item.total_price }}</h5>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12 col-lg-3">
                                                    <div class="cart-action text-center">
                                                        <form id="{{ forloop.counter }}"
                                                              action="{% url 'cart:add' product.slug %}"
                                                              method="POST">
                                                            {% csrf_token %}
                                                            {{ item.update_quantity_form.quantity }}
                                                            {{ item.update_quantity_form.update }}
                                                        </form>

                                                    </div>
                                                </div>
                                                <div class="col-12 col-lg-3">
                                                    <div class="text-center">
                                                        <div class="d-flex gap-2 justify-content-center justify-content-lg-end">
                                                            <button form="{{ forloop.counter }}" type="submit"
                                                                    class="btn btn-dark rounded-0 btn-ecomm">
                                                                <i class='bx bx-refresh'></i></button>
                                                            <a href="{% url 'cart:remove' product.slug %}"
                                                               class="btn btn-dark rounded-0 btn-ecomm"><i
                                                                    class='bx bx-x-circle'></i> {% trans 'Remove' %}</a>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="my-4 border-top"></div>
                                        {% endwith %}
                                    {% empty %}
                                        <div class="row align-items-center g-3">
                                        {% blocktrans trimmed %}
                                            <h3>Your Cart is Empty</h3>
                                            <p>Add something to make me happy :)</p>
                                        {% endblocktrans %}
                                        </div>
                                        <div class="my-4 border-top"></div>
                                    {% endfor %}
                                    <div class="d-lg-flex align-items-center gap-2"><a href="{% url 'shop:index' %}"
                                                                                       class="btn btn-dark btn-ecomm"><i
                                            class='bx bx-shopping-bag'></i> {% trans 'Continue Shopping' %}</a>
                                        <a href="{% url 'cart:clear' %}" class="btn btn-light btn-ecomm ms-auto"><i
                                                class='bx bx-x-circle'></i> {% trans 'Clear Cart' %}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-4">
                                <div class="checkout-form p-3 bg-light">
                                    <div class="card rounded-0 border bg-transparent shadow-none">
                                        <form action="{% url 'coupons:apply' %}" method="POST" class="card-body">{% csrf_token %}
                                            <p class="fs-5">{{ coupon_form.code.label }}</p>
                                            <div class="input-group">
                                                {{ coupon_form.code }}
                                                <button class="btn btn-dark btn-ecomm" type="submit">{% trans 'Apply Discount' %}
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card rounded-0 border bg-transparent mb-0 shadow-none">
                                        <div class="card-body">
                                            <p class="mb-2">{% trans 'Subtotal:' %} <span class="float-end">${{ cart.get_total_price }}</span>
                                            </p>
                                            <p class="mb-0">{% trans 'Discount:' %} <span class="float-end">{% if cart.coupon %}{{ cart.coupon }} - ${{ cart.get_discount }}{% else %}--{% endif %}</span>
                                            </p>
                                            <div class="my-3 border-top"></div>
                                            <h5 class="mb-0">{% trans 'Order Total:' %} <span class="float-end">${{ cart.get_total_price_after_discount }}</span></h5>
                                            <div class="my-4"></div>
                                            <div class="d-grid"><a href="{% url 'orders:order_create' %}" class="btn btn-dark btn-ecomm">{% trans 'Proceed to Checkout' %}</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--end row-->
                    </div>
                </div>
            </section>
            <!--end shop cart-->
        </div>
    </div>
    <!--end page wrapper -->
{% endblock content %}