cart/urls.py
from django.urls import path

from cart.views import CartDetailView, AddToCartView, RemoveFromCartView, clear_cart


app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', AddToCartView.as_view(), name='add'),
    path('remove/<slug:slug>/', RemoveFromCartView.as_view(), name='remove'),
    path('clear/', clear_cart, name='clear'),
]

customers/urls.py
from django.urls import path
from customers.views import ProfileDetailView, CustomerUpdateView, CustomerChangePassword


app_name = 'customers'

urlpatterns = [
    path('profile/<int:pk>/dashboard/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<int:pk>/details/', CustomerUpdateView.as_view(), name='details'),
    path('profile/<int:pk>/change-password/', CustomerChangePassword.as_view(), name='change_password'),
]

favorites/urls.py
from django.urls import path

from favorites.views import AddToFavoritesView, FavoritesView, RemoveFromFavoritesView, favorites_api

app_name = 'favorites'

urlpatterns = [
    path('', FavoritesView.as_view(), name='list'),
    path('add/', AddToFavoritesView.as_view(), name='add'),
    path('remove/', RemoveFromFavoritesView.as_view(), name='remove'),
    path('api/', favorites_api, name='api'),
]

shop/urls.py
from django.urls import path

from shop.views import (
    IndexTemplateView,
    CategoryProductsListView,
    DeliveryView,
    AboutView,
    ContactsView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('category/<slug:slug>/', CategoryProductsListView.as_view(), name='category_products'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

tyres_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from orders.views import StripeWebhookView
from shop.views import get_specifications


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('webhooks/stripe/', StripeWebhookView.as_view(), name='stripe_webhook'),
    path('get_specifications/<int:product_type_id>/', get_specifications, name='get_specifications'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include("django.conf.urls.i18n")),
    path('customers/', include('customers.urls', namespace='customers')),
    path('accounts/', include('allauth.urls')),  # Allauth
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

favorites/models.py
from django.db import models

# Create your models here.

favorites/views.py
from django.contrib.contenttypes.models import ContentType
from django.db.models import Avg, Count
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView
from django.utils.translation import gettext_lazy as _

from favorites.utils import Favorite
from shop.models import Product


class AddToFavoritesView(View):
    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('id')
        favorites = Favorite(request)
        favorites.add(product_id)
        response_data = {
            'id': request.POST.get('id'),
        }
        return JsonResponse(data=response_data)


class RemoveFromFavoritesView(View):
    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('id')
        favorites = Favorite(request)
        favorites.remove(product_id)
        response_data = {
            'id': request.POST.get('id'),
        }
        return JsonResponse(data=response_data)


class FavoritesView(ListView):
    template_name = 'favorites/favorites_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        favorites = self.request.session.get('favorites')
        queryset = Product.objects.filter(id__in=favorites). \
            select_related('category').prefetch_related('images', 'ratings').annotate(
            avg_rating=Avg('ratings__value'),
            users_count=Count('ratings__ip')
        ).only('category', 'ratings', 'images', 'name', 'price', 'slug', 'status')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Shop|Favorites')
        return context


def favorites_api(request):
    """Sends actual favorites to JS."""
    return JsonResponse(request.session.get('favorites'), safe=False)

favorites/templates/favorites/favorites_list.html
{% extends 'base.html' %}
{% load static %}
{% load shop_tags i18n %}
{% block content %}
		<!--start page wrapper -->
		<div class="page-wrapper">
			<div class="page-content">
				<!--start breadcrumb-->
				<section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
					<div class="container">
						<div class="page-breadcrumb d-flex align-items-center">
							<h3 class="breadcrumb-title pe-3">{% trans 'Wishlist' %}</h3>
							<div class="ms-auto">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb mb-0 p-0">
										<li class="breadcrumb-item"><a href="{% url 'shop:index' %}"><i class="bx bx-home-alt"></i> {% trans 'Home' %}</a></li>
                                        {% if user.is_authenticated %}
										<li class="breadcrumb-item"><a href="{% url 'customers:profile' user.id %}">{% trans 'Account' %}</a></li>
                                        {% endif %}
										<li class="breadcrumb-item active" aria-current="page">{% trans 'Wishlist' %}</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</section>
				<!--end breadcrumb-->
				<!--start Featured product-->
				<section class="py-4">
					<div class="container">
						<div class="product-grid">
							<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-3">
                                {% for product in products %}
								<div class="col">
									<div class="card rounded-0 product-card">
										<a href="{{ product.get_absolute_url }}">
                                            {% get_main_image product as image_obj %}
                                                    {% if image_obj %}
                                                        <img src="{{ image_obj.image.url }}" class="card-img-top" alt="{{ image_obj.alt_text }}">
                                                    {% else %}
                                                        <img src="{% static 'assets/images/products/no_image.png' %}" class="card-img-top" alt="...">
                                                    {% endif %}
										</a>
										<div class="card-body">
											<div class="product-info">
												<a href="{% url 'shop:category_products' product.category.slug %}">
													<p class="product-catergory font-13 mb-1">{{ product.category.name }}</p>
												</a>
												<a href="{{ product.get_absolute_url }}">
													<h6 class="product-name mb-2">{{ product.name }}</h6>
												</a>
												<div class="d-flex align-items-center">
													<div class="mb-1 product-price">
                                                        {% if product.status != 0 %}
                                                        <span class="me-1 text-decoration-line-through">$99.00</span>
                                                        <span class="fs-5">${{ product.price }}</span>
                                                        {% else %}
                                                            <span class="me-1">{% trans 'Out of stock' %}</span>
                                                        {% endif %}
                                                    </div>
													 {% show_rating product %}
												</div>
												<div class="product-action mt-2">
													<div class="d-grid gap-2">
														<a href="{% url 'cart:add' product.slug %}" class="btn btn-white btn-ecomm">	<i class='bx bxs-cart-add'></i>{% trans 'Add to Cart' %}</a>
														<div data-id="{{ product.id }}" class="remove-from-favorites btn btn-light btn-ecomm"><i class='bx bx-heart'></i>{% trans 'Remove From Wishlist' %}</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
                                {% empty %}
                                    <p>{% trans "You don't have any favorites yet." %}</p>
			                    {% endfor %}
							</div>
							<!--end row-->
						</div>
					</div>
				</section>
				<!--end Featured product-->
			</div>
		</div>
		<!--end page wrapper -->
{% endblock content %}