cart/urls.py
from django.urls import path

from cart.views import CartDetailView, AddToCartView, RemoveFromCartView, clear_cart


app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', AddToCartView.as_view(), name='add'),
    path('remove/<slug:slug>/', RemoveFromCartView.as_view(), name='remove'),
    path('clear/', clear_cart, name='clear'),
]

coupons/urls.py
from django.urls import path
from coupons.views import CouponApplyView


app_name = 'coupons'

urlpatterns = [
    path('apply/', CouponApplyView.as_view(), name='apply'),
]

customers/urls.py
from django.urls import path
from customers.views import ProfileDetailView, CustomerUpdateView, CustomerChangePassword


app_name = 'customers'

urlpatterns = [
    path('profile/<int:pk>/dashboard/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<int:pk>/details/', CustomerUpdateView.as_view(), name='details'),
    path('profile/<int:pk>/change-password/', CustomerChangePassword.as_view(), name='change_password'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderDetailsView, OrderCreateView, OrdersListView, admin_order_details, OrderDeleteView, \
    SuccessView, CancelView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('list/', OrdersListView.as_view(), name='order_list'),
    path('details/<int:order_id>/', OrderDetailsView.as_view(), name='order_details'),
    path('admin/order/<int:order_id>/', admin_order_details, name='admin_order_details'),
    path('<pk>/delete/', OrderDeleteView.as_view(), name='delete'),
    path('success/', SuccessView.as_view(), name='success'),
    path('cancel/', CancelView.as_view(), name='cancel')
]

shop/urls.py
from django.urls import path

from shop.views import (
    IndexTemplateView,
    CategoryProductsListView,
    DeliveryView,
    AboutView,
    ContactsView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('category/<slug:slug>/', CategoryProductsListView.as_view(), name='category_products'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

tyres_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from orders.views import StripeWebhookView
from shop.views import get_specifications


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('webhooks/stripe/', StripeWebhookView.as_view(), name='stripe_webhook'),
    path('get_specifications/<int:product_type_id>/', get_specifications, name='get_specifications'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include("django.conf.urls.i18n")),
    path('customers/', include('customers.urls', namespace='customers')),
    path('accounts/', include('allauth.urls')),  # Allauth
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from decimal import Decimal

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from customers.models import Customer
from coupons.models import Coupon
from shop.models import Product


class Order(models.Model):
    customer = models.ForeignKey(Customer, related_name='orders', on_delete=models.CASCADE, verbose_name=_('Customer'))
    first_name = models.CharField(_('First name'), max_length=100)
    last_name = models.CharField(_('Last name'), max_length=100)
    email = models.EmailField()
    phone = models.CharField(_('Phone'), max_length=50)
    country = models.CharField(_('Country'), max_length=70)
    zip = models.IntegerField(_('Zip'))
    address = models.TextField(_('Address'), max_length=300)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    paid = models.BooleanField(_('Paid'), default=False)
    delivery = models.ForeignKey('Delivery', related_name='orders', on_delete=models.CASCADE, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, related_name='orders', null=True, blank=True)
    discount = models.SmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = self.get_total_cost_before_discount()
        return total_cost - self.get_discount()

    def get_total_quantity(self):
        return sum(item.quantity for item in self.items.all())

    def stripe_products(self):
        order_items = self.items.all()
        line_items = []
        for item in order_items:
            line_item = {
                'price': item.product.stripe_product_price_id,
                'quantity': item.quantity
            }
            line_items.append(line_item)
        return line_items

    def get_total_cost_before_discount(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_discount(self):
        total_cost = self.get_total_cost_before_discount()
        if self.discount:
            return total_cost * (self.discount / Decimal(100))
        return Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.id

    def get_cost(self):
        return self.price * self.quantity


class Delivery(models.Model):
    method = models.CharField(_('Method'), max_length=50)
    cost = models.PositiveSmallIntegerField(_('Cost'), default=0)

    class Meta:
        verbose_name = _('Delivery')
        verbose_name_plural = _('Deliveries')

    def __str__(self):
        return f'{self.method}\t+{self.cost}$/pcs.'

orders/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Order, Delivery


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone']
        template_input_class = 'form-control rounded-0'
        widgets = {
            'first_name': forms.TextInput(attrs={'class': template_input_class}),
            'last_name': forms.TextInput(attrs={'class': template_input_class}),
            'phone': forms.TextInput(attrs={'class': template_input_class}),
            'email': forms.EmailInput(attrs={
                'class': template_input_class,
                'id': 'inputEmailAddress',
                'placeholder': 'user@example.com'
            }),
        }


class OrderAddressForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['country', 'zip', 'address']
        template_input_class = 'form-control rounded-0'
        widgets = {
            'country': forms.TextInput(attrs={'class': template_input_class}),
            'zip': forms.TextInput(attrs={'class': template_input_class}),
            'address': forms.Textarea(attrs={'class': template_input_class}),
        }


class OrderDeliveryMethodForm(forms.ModelForm):
    delivery = forms.ModelChoiceField(
        queryset=Delivery.objects.all(),
        empty_label=None,
        label=_('Choose method'),
        widget=forms.RadioSelect()
    )

    class Meta:
        model = Order
        fields = ['delivery']

orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, TemplateView, DeleteView
from formtools.wizard.views import SessionWizardView

from cart.cart import Cart
from coupons.forms import CouponApplyForm
from customers.models import Customer
from orders.forms import OrderCreateForm, OrderAddressForm, OrderDeliveryMethodForm
from orders.models import Order, OrderItem
from shop.models import ProductStatistic


class OrderCreateView(SessionWizardView):
    form_list = [OrderCreateForm, OrderAddressForm, OrderDeliveryMethodForm]
    template_name = 'orders/order/order_create.html'

    def get_form_initial(self, step):
        user = self.request.user
        initial = self.initial_dict.get(step, {})
        initial.update(
            {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email,
                'phone': user.phone,
                'address': user.address
            }
        )
        return initial

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form, **kwargs)
        context['coupon_form'] = CouponApplyForm()
        context['title'] = 'Shop|Checkout'
        return context

    def done(self, form_list, **kwargs):
        cart = Cart(self.request)
        order = form_list[0].save(commit=False)
        order.customer = Customer.objects.get(pk=self.request.user.pk)
        order.country = form_list[1].cleaned_data['country']
        order.zip = form_list[1].cleaned_data['zip']
        order.address = form_list[1].cleaned_data['address']
        order.delivery = form_list[-1].cleaned_data['delivery']
        if cart.coupon:
            order.coupon = cart.coupon
            order.discount = cart.coupon.discount
        order.save()

        for item in cart:
            OrderItem.objects.create(order=order,
                                     product=item['product'],
                                     price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        # Create a checkout session and redirect the user to Stripe's checkout page.
        session_data = {
            'payment_method_types': ['card'],
            'metadata': {'order_id': order.id},
            'mode': 'payment',
            'line_items': order.stripe_products(),
            'success_url': f'{settings.DOMAIN_NAME}{reverse("orders:success")}',
            'cancel_url': f'{settings.DOMAIN_NAME}{reverse("orders:cancel")}',
        }
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon,
                percent_off=order.discount,
                duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]
        checkout_session = stripe.checkout.Session.create(**session_data)
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)


class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'orders/order/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('orders:order_list')


class OrdersListView(ListView):
    template_name = 'orders/order/user_orders.html'
    context_object_name = 'orders'
    extra_context = {'title': 'Shop|Orders'}

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)


class OrderDetailsView(ListView):
    template_name = 'orders/order/order_details.html'
    context_object_name = 'order'

    def get_queryset(self):
        order = Order.objects.get(id=self.kwargs['order_id'])
        return order.items.all()


@method_decorator(csrf_exempt, name="dispatch")
class StripeWebhookView(View):
    """
    Stripe webhook view to handle checkout session completed event.
    """
    order = None

    def post(self, request):
        payload = request.body
        endpoint_secret = settings.STRIPE_WEBHOOK_SECRET
        sig_header = request.META["HTTP_STRIPE_SIGNATURE"]

        try:
            event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
        except ValueError:
            # Invalid payload
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)
        except stripe.error.SignatureVerificationError:
            # Invalid signature
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        if event["type"] == "checkout.session.completed":
            session = event.data.object

            self.set_order_paid(session)
            self.set_sales_quantity()
        # Can handle other events here.

        return HttpResponse(status=HTTPStatus.OK)

    def set_order_paid(self, session):
        order_id = session.metadata.order_id
        self.order = get_object_or_404(Order, id=order_id)
        self.order.paid = True
        self.order.save()

    def set_sales_quantity(self):
        for item in self.order.items.all():
            obj, _ = ProductStatistic.objects.get_or_create(
                product=item.product,
                date=timezone.now(),
                defaults={'product': item.product, 'date': timezone.now()},
            )
            obj.purchases_quantity += item.quantity
            obj.save(update_fields=['purchases_quantity'])


class SuccessView(TemplateView):
    template_name = 'orders/payments/success.html'


class CancelView(TemplateView):
    template_name = 'orders/payments/cancel.html'


@staff_member_required
def admin_order_details(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/orders/order/order_details.html', {'order': order})

orders/templates/orders/order/confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="page-wrapper">
        <div class="page-content">
            <hr>
            <section class="py-4">
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        <h1>{% blocktrans with order=object %}Are you sure, you want to delete "{{ order }}"?{% endblocktrans %}</h1>
                        <button type="submit" class="btn btn-danger btn-sm text-uppercase rounded-0 font-13 fw-500">
                            {% trans 'Confirm Delete' %}
                        </button>
                    </form>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/order_details.html
{% extends 'base.html' %}
{% load static shop_tags i18n %}
{% block content %}
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">
            <!--start breadcrumb-->
            <section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
                <div class="container">
                    <div class="page-breadcrumb d-flex align-items-center">
                        <h3 class="breadcrumb-title pe-3">{% trans 'Order' %} # {{ view.kwargs.order_id }}</h3>
                        <div class="ms-auto">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb mb-0 p-0">
                                    <li class="breadcrumb-item"><a href="{% url 'shop:index' %}"><i class="bx bx-home-alt"></i>
                                        {% trans 'Home' %}</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{% url 'orders:order_list' %}">{% trans 'Orders' %}</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">{% trans 'Order details' %}</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </section>
            <!--end breadcrumb-->
            <!--start shop cart-->
            <section class="py-4">
                <div class="container">
                    <div class="shop-cart">
                        <div class="row">
                            <div class="col-12 col-xl-12">
                                <div class="shop-cart-list mb-3 p-3">
                                    {% for item in order %}
                                        {% with product=item.product %}
                                            <div class="row align-items-center g-3">
                                                <div class="col-12 col-lg-6">
                                                    <div class="d-lg-flex align-items-center gap-2">
                                                        <div class="cart-img text-center text-lg-start">
                                                            {% get_main_image product as image_obj %}
                                                        <a href="{{ product.get_absolute_url }}">
                                                            <img src="{{ image_obj.image.url }}" width="130" alt="{{ image_obj.alt_text }}">
                                                        </a>
                                                        </div>
                                                        <div class="cart-detail text-center text-lg-start">
                                                            <a href="{{ product.get_absolute_url }}"><h6 class="mb-2">{{ product.name }}</h6></a>
                                                            <p class="mb-0">{% trans 'Diameter' %}: <span>{{ product.diameter }}</span>
                                                            </p>
                                                            <p class="mb-2">{% trans 'Price' %}: <span>${{ item.price }} x {{ item.quantity }}{% trans 'pcs.' %}</span>
                                                            </p>
                                                            <h5 class="mb-0">${{ item.get_cost }}</h5>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="my-4 border-top"></div>
                                        {% endwith %}
                                    {% endfor %}
                                    <div class="d-lg-flex align-items-center gap-2"><a href="{% url 'shop:index' %}"
                                                                                       class="btn btn-dark btn-ecomm"><i
                                            class='bx bx-shopping-bag'></i> {% trans 'Continue Shopping' %}</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!--end row-->
                    </div>
                </div>
            </section>
            <!--end shop cart-->
        </div>
    </div>
    <!--end page wrapper -->
{% endblock content %}

orders/templates/orders/order/order_summary.html
{% load shop_tags i18n %}
<div class="col-12 col-xl-4">
    <div class="order-summary">
        <div class="card rounded-0">
            <div class="card-body">
                <div class="card rounded-0 border bg-transparent shadow-none">
                    <div class="card-body">
                        <p class="fs-5">{{ coupon_form.code.label }}</p>
                        <form action="{% url 'coupons:apply' %}" method="POST" class="input-group">
                            {% csrf_token %}
                            {{ coupon_form.code }}
                            <button class="btn btn-dark btn-ecomm" type="submit">{% trans 'Apply Discount' %}</button>
                        </form>
                    </div>
                </div>
                <div class="card rounded-0 border bg-transparent shadow-none">
                    <div class="card-body">
                        <p class="fs-5">{% trans 'Order summary' %}</p>
                        {% for item in cart %}
                            {% with product=item.product %}
                        <div class="my-3 border-top"></div>
                        <div class="d-flex align-items-center">
                        {% get_main_image product as image_obj %}
                            <a class="d-block flex-shrink-0" href="{{ product.get_absolute_url }}">
                                <img src="{{ image_obj.image.url }}" width="75" alt="Product">
                            </a>
                            <div class="ps-2">
                                <h6 class="mb-1"><a href="{{ product.get_absolute_url }}" class="text-dark">{{ product.name }}</a></h6>
                                <div class="widget-product-meta">
                                    <span class="me-2">${{ item.price }}</span>
                                    <span class="">x {{ item.quantity }}</span>
                                </div>
                            </div>
                        </div>
                            {% endwith %}
                        {% endfor %}
                    </div>
                </div>
                <div class="card rounded-0 border bg-transparent mb-0 shadow-none">
                    <div class="card-body">
                        <p class="mb-2">{% trans 'Subtotal' %}: <span class="float-end">${{ cart.get_total_price }}</span>
                        </p>
                        <p class="mb-2">{% trans 'Shipping' %}: <span class="float-end">--</span>
                        </p>
                        <p class="mb-0">{% trans 'Discount' %}: <span class="float-end">{% if cart.coupon %}{{ cart.coupon }} - ${{ cart.get_discount }}{% else %}--{% endif %}</span>
                        </p>
                        <div class="my-3 border-top"></div>
                        <h5 class="mb-0">{% trans 'Order Total' %}: <span class="float-end">${{ cart.get_total_price_after_discount }}</span>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

orders/templates/orders/order/user_orders.html
{% extends 'base.html' %}
{% load static i18n %}
{% block content %}
		<!--start page wrapper -->
		<div class="page-wrapper">
			<div class="page-content">
				<!--start breadcrumb-->
				<section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
					<div class="container">
						<div class="page-breadcrumb d-flex align-items-center">
							<h3 class="breadcrumb-title pe-3">{% trans 'My Orders' %}</h3>
							<div class="ms-auto">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb mb-0 p-0">
										<li class="breadcrumb-item"><a href="{% url 'shop:index' %}"><i class="bx bx-home-alt"></i> {% trans 'Home' %}</a>
										</li>
										<li class="breadcrumb-item"><a href="{% url 'customers:profile' user.pk %}">{% trans 'Account' %}</a>
										</li>
										<li class="breadcrumb-item active" aria-current="page">{% trans 'My Orders' %}</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</section>
				<!--end breadcrumb-->
				<!--start shop cart-->
				<section class="py-4">
					<div class="container">
						<h3 class="d-none">{% trans 'Account' %}</h3>
						<div class="card">
							<div class="card-body">
								<div class="row">
									{% include 'customers/customer_menu.html' %}
									<div class="col-lg-8">
										<div class="card shadow-none mb-0">
											<div class="card-body">
                                            {% if orders %}
												<div class="table-responsive">
													<table class="table">
                                                    <caption>{% trans 'My Orders' %}</caption>
														<thead class="table-light">
															<tr>
																<th>{% trans 'Order' %}</th>
																<th>{% trans 'Date' %}</th>
																<th>{% trans 'Status' %}</th>
																<th>{% trans 'Total' %}</th>
																<th>{% trans 'Actions' %}</th>
															</tr>
														</thead>
														<tbody>
                                                        {% for order in orders %}
															<tr>
																<td>#{{ order.id }}</td>
																<td>{{ order.created|date:'D, d M Y H:i' }}</td>
																<td>
                                                                    {% if order.paid %}
																	<div class="badge rounded-pill bg-success w-100">{% trans 'Paid' %}</div>
                                                                    {% else %}
                                                                    <div class="badge rounded-pill bg-danger w-100">{% trans 'Unpaid' %}</div>
                                                                    {% endif %}
																</td>
																<td>{% blocktrans trimmed with total_cost=order.get_total_cost count total_qty=order.get_total_quantity %}
                                                                    ${{ total_cost }} for {{ total_qty }} item
                                                                {% plural %}
                                                                    ${{ total_cost }} for {{ total_qty }} items
                                                                {% endblocktrans %}</td>
																<td>
																	<div class="d-flex gap-2">
                                                                        <a href="{% url 'orders:order_details' order.id %}" class="btn btn-dark btn-sm rounded-0">{% trans 'View' %}</a>
                                                                        {% if not order.paid %}
                                                                        <a href="{% url 'orders:order_create' %}" class="btn btn-dark btn-sm rounded-0">{% trans 'Pay' %}</a>
																		<a href="{% url 'orders:delete' order.id %}" class="btn btn-dark btn-sm rounded-0">{% trans 'Cancel' %}</a>
                                                                        {% endif %}
																	</div>
																</td>
															</tr>
                                                        {% endfor %}
														</tbody>
													</table>
												</div>
                                            {% else %}
                                            <p>{% trans 'There are no orders.' %}</p>
                                            {% endif %}
											</div>
										</div>
									</div>
								</div>
								<!--end row-->
							</div>
						</div>
					</div>
				</section>
				<!--end shop cart-->
			</div>
		</div>
		<!--end page wrapper -->
		<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		<!--End Back To Top Button-->
{% endblock content %}