cart/urls.py
from django.urls import path

from cart.views import CartDetailView, AddToCartView, RemoveFromCartView, clear_cart


app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', AddToCartView.as_view(), name='add'),
    path('remove/<slug:slug>/', RemoveFromCartView.as_view(), name='remove'),
    path('clear/', clear_cart, name='clear'),
]

ratings/urls.py
from django.urls import path

from ratings.views import SetRatingView


app_name = 'ratings'

urlpatterns = [
    path('set_rating/', SetRatingView.as_view(), name='set_rating'),
]

shop/urls.py
from django.urls import path

from shop.views import (
    IndexTemplateView,
    CategoryProductsListView,
    DeliveryView,
    AboutView,
    ContactsView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('category/<slug:slug>/', CategoryProductsListView.as_view(), name='category_products'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

tyres_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from orders.views import StripeWebhookView
from shop.views import get_specifications


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('webhooks/stripe/', StripeWebhookView.as_view(), name='stripe_webhook'),
    path('get_specifications/<int:product_type_id>/', get_specifications, name='get_specifications'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include("django.conf.urls.i18n")),
    path('customers/', include('customers.urls', namespace='customers')),
    path('accounts/', include('allauth.urls')),  # Allauth
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratings/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from shop.models import Product


class Rating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='ratings')
    ip = models.CharField(max_length=15)
    value = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return f'ip={self.ip} value:{self.value}'

ratings/views.py
import json

from django.contrib.contenttypes.models import ContentType
from django.db.models import Avg
from django.http import JsonResponse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from ratings.models import Rating
from shop.models import Product


class SetRatingView(View):
    """Logged users only can set rating."""

    def get_user_ip(self):
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        return ip

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        request_data = json.loads(request.body)
        product = Product.objects.get(id=request_data['product_id'])
        Rating.objects.update_or_create(
            ip=self.get_user_ip(),
            product=product,
            defaults={'value': request_data['user_rating']}
        )
        new_rating = product.ratings.aggregate(avg_value=Avg('value'))
        response_data = {
            'new_rating': round(new_rating['avg_value'], 1),
        }
        return JsonResponse(data=response_data)

templates/menu.html
{% load i18n %}
<div class="primary-menu border-top">
    <div class="container">
        <nav id="navbar_main" class="mobile-offcanvas navbar navbar-expand-lg">
            <div class="offcanvas-header">
                <button class="btn-close float-end"></button>
                <h5 class="py-2">{% trans 'Navigation' %}</h5>
            </div>
            <ul class="navbar-nav">
                {% for cat in cats %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:category_products' cat.slug %}">{{ cat.name }}</a>
                    </li>
                {% endfor %}
                {% for menu_item in menu %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url menu_item.url_name %}">{{ menu_item.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

templates/modal.html
{% load static i18n %}
    <!--start quick view product-->
    <!-- Modal -->
    <div class="modal fade" id="QuickViewProduct">
        <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen-xl-down">
            <div class="modal-content rounded-0 border-0">
                <div class="modal-body">
                    <button type="button" class="btn-close float-end" data-bs-dismiss="modal"></button>
                    <div class="row g-0">
                       	<div class="col-12 col-lg-6">
								<div class="image-zoom-section"></div>
							</div>
                        <div class="col-12 col-lg-6">
                            <div class="product-info-section p-3">
                                <h3 class="mt-3 mt-lg-0 mb-0 modal-title"></h3>
                                <hr>
                                <div class="d-flex align-items-center mt-3 gap-2">
                                    <h5 class="mb-0 text-light-3">{% trans 'Price:' %}</h5>
                                    <h4 class="mb-0 modal-price"></h4>
                                </div>
                                <div class="mt-3">
                                    <h6>{% trans 'Description' %} :</h6>
                                    <p class="mb-0 modal-desc"></p>
                                </div>
                                <dl class="row mt-3">
                                    <dt class="col-sm-3">{% trans 'Prod.SKU' %} :</dt>
                                    <dd class="col-sm-9 modal-sku"></dd>
                                    <dt class="col-sm-3">{% trans 'Delivery' %} :</dt>
                                    <dd class="col-sm-9">Ukraine, USA, and Europe</dd>
                                </dl>
                                <hr>
                                <div class="row row-cols-auto align-items-center mt-3">
                                    <div class="col form">
                                        <form id="addToCartForm" name="modal_cart_form" action="" method="post">
                                             {% csrf_token %}
                                            <label for="{{ form.quantity.id_for_label }}"
                                                   class="form-label">{{ form.quantity.label }}</label>
                                            {{ form.quantity }}
                                        </form>
                                    </div>
                                </div>
                                <div class="d-flex gap-2 mt-3 form-buttons">
                                    <button name="btn" form="addToCartForm" type="submit" class="btn btn-primary btn-ecomm"><i class="bx bxs-cart-add"></i>{% trans 'Add to Cart' %}</button>
                                    <a href="javascript:;" class="btn btn-light btn-ecomm"><i
                                            class="bx bx-heart"></i>{% trans 'Add to Wishlist' %}</a>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!--end row-->
                </div>
            </div>
        </div>
    </div>
    <!--end quick view product-->

templates/rating.html
{% load l10n %}

<div data-id="{{ product_id }}" data-ajax="true" class="rating rating__set">
    <div class="rating__body">
        <div class="rating__active"></div>
        <div class="rating__items">
            <input type="radio" class="rating__item" value="1" name="rating">
            <input type="radio" class="rating__item" value="2" name="rating">
            <input type="radio" class="rating__item" value="3" name="rating">
            <input type="radio" class="rating__item" value="4" name="rating">
            <input type="radio" class="rating__item" value="5" name="rating">
        </div>
    </div>
    <!-- You must send rating value to JS with decimal separator "." for correct work on other locale language.  -->
    <div class="rating__value">{{ rating|unlocalize }}</div>
</div>

templates/search_form.html
<form class="input-group flex-nowrap px-xl-4" method="get" action="{% url 'shop:search' %}">
    {{ search_form }}
    <button type="submit" class="input-group-text cursor-pointer bg-transparent"><i class='bx bx-search'></i></button>
</form>